services:
  k6-load:
    image: grafana/k6:latest
    user: root
    environment:
      - K6_NO_USAGE_REPORT=true
      - API_HOST=lb:9999
    volumes:
      - ./test:/test
    working_dir: /test
    command: run /test/test.js
    depends_on:
      lb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 8G
